on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet Package
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'preview'
      - name: Build
        run: dotnet build -c Release
      - name: Pack
        run: dotnet pack ./src/Rig.Api/Rig.Api.csproj -c Release --no-build --output /p:Version=${{ github.event.release.tag_name }} .      
      - name: Pack
        run: dotnet pack ./src/Rig.CosmosDb/Rig.CosmosDb.csproj  -c Release --no-build --output /p:Version=${{ github.event.release.tag_name }} .      
      - name: Pack
        run: dotnet pack ./src/Rig.Domain/Rig.Domain.csproj  -c Release --no-build --output /p:Version=${{ github.event.release.tag_name }} .
      - name: Push
        run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
